switch:
  - platform: mqtt
    unique_id: Humidifier_Basement
    name: "Humidifier-Basement"
    state_topic: "home/humidifier/state/basement"
    value_template: >-
      {% if (value_json.enabled)%}
       on
      {% else %}
       off
      {% endif %}
    command_topic: "home/humidifier/command/vsaq7588f6f84290868639af8c171175"
    payload_on: "on"
    payload_off: "off"
    json_attributes_topic: "home/humidifier/state/basement"
    json_attributes_template: "{{ value_json | tojson }}"

  - platform: mqtt
    unique_id: Humidifier_Upstairs
    name: "Humidifier-Upstairs"
    state_topic: "home/humidifier/state/upstairs"
    value_template: >-
      {% if (value_json.enabled)%}
       on
      {% else %}
       off
      {% endif %}
    command_topic: "home/humidifier/command/vsaq7de16d3b4db2bae840277b436b61"
    payload_on: "on"
    payload_off: "off"
    json_attributes_topic: "home/humidifier/state/upstairs"
    json_attributes_template: "{{ value_json | tojson }}"